# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: blog-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog1234
      POSTGRES_DB: blog
    volumes:
      - blog-data:/var/lib/postgresql/data

volumes:
  blog-data:
